export const Genders = [
  { id: 1, label: 'Man' },
  { id: 2, label: 'Woman' },
  { id: 3, label: 'Nonbinary' },
];

export const GenderIdentities = {
  Man: [
    { id: 1, label: 'Intersex man' },
    { id: 2, label: 'Trans man' },
    { id: 3, label: 'Transmasculine' },
    { id: 4, label: 'Man & nonbinary' },
    { id: 5, label: 'Cis man' },
  ],
  Woman: [
    { id: 1, label: 'Intersex woman' },
    { id: 2, label: 'Trans woman' },
    { id: 3, label: 'Transfeminine' },
    { id: 4, label: 'woman & nonbinary' },
    { id: 5, label: 'Cis woman' },
  ],
  Nonbinary: [
    { id: 1, label: 'Agender' },
    { id: 2, label: 'Bigender' },
    { id: 3, label: 'Genderfluid' },
    { id: 4, label: 'Genderqueer' },
    { id: 5, label: 'Gender nonconforming' },
    { id: 6, label: 'Gender questioning' },
    { id: 7, label: 'Gender variant' },
    { id: 8, label: 'Intersex' },
    { id: 9, label: 'Intersex man' },
    { id: 10, label: 'Intersex woman' },
    { id: 11, label: 'Neutrois' },
    { id: 12, label: 'Nonbinary man' },
    { id: 13, label: 'Nonbinary woman' },
    { id: 14, label: 'Pangender' },
    { id: 15, label: 'Polygender' },
    { id: 16, label: 'Transgender' },
    { id: 17, label: 'Trans man' },
    { id: 18, label: 'Transmasculine' },
    { id: 19, label: 'Trans woman' },
    { id: 20, label: 'Transfeminine' },
    { id: 21, label: 'Two-spirit' },
  ],
};

// export const GenderIdentities = {
//   Man: [
//     'Intersex man',
//     'Trans man',
//     'Transmasculine',
//     'Man & nonbinary',
//     'Cis man',
//   ],
//   Woman: [
//     'Intersex woman',
//     'Trans woman',
//     'Transfeminine',
//     'woman & nonbinary',
//     'Cis woman',
//   ],
//   Nonbinary: [
//     'Agender',
//     'Bigender',
//     'Genderfluid',
//     'Genderqueer',
//     'Gender nonconforming',
//     'Gender questioning',
//     'Gender variant',
//     'Intersex',
//     'Intersex man',
//     'Intersex woman',
//     'Neutrois',
//     'Nonbinary man',
//     'Nonbinary woman',
//     'Pangender',
//     'Polygender',
//     'Transgender',
//     'Trans man',
//     'Transmasculine',
//     'Trans woman',
//     'Transfeminine',
//     'Two-spirit',
//   ],
// };
