export const IDRequiredFields = [
  'FIRST_NAME',
  'LAST_NAME',
  'CITY_IN_ADDRESS',
  'ZIP_CODE_IN_ADDRESS',
  'STATE_IN_ADDRESS',
  'STATE_NAME',
  'EXPIRATION_DATE',
  'DATE_OF_BIRTH',
  'DATE_OF_ISSUE',
  'ID_TYPE',
];

export const IDType = ['DRIVER LICENSE FRONT', 'DRIVER LICENSE BACK'];
